[package]
name = "fs"
version = "1.0.0"
edition = "2021"
authors = ["Norio Yahata"]
license = "MIT"

[dependencies]
# Web Server
actix-rt = "2"
actix-web = { version = "4", features = ["openssl"] }
actix-files = "0.6.0"
openssl = { version = "0.10", features = ["v110"] }
