[package]
name = "fs"
version = "1.0.0"
edition = "2021"
authors = ["Norio Yahata"]
license = "MIT"

[dependencies]
# Web Server
actix-rt = "2"
actix-web = { version = "4.0.0-beta.18", default_features = false }
actix-cors = "0.6.0-beta.7"
actix-files = "0.6.0-beta.7"
